<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>Vestiges</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Steamworks.NET" Version="2024.8.0" />
  </ItemGroup>
</Project>
